task: vision_classification
dataset: cifar10
data:
  root: data/raw

model:
  name: resnet18
  num_classes: 10

optimizer:
  name: adam
  lr: 0.001
  weight_decay: 0.0001

scheduler:
  name: step_lr
  step_size: 1
  gamma: 0.9

training:
  epochs: 3
  batch_size: 128
  num_workers: 2
  val_split: 0.1
  seed: 42
  device: auto
  pin_memory: true
  early_stopping_patience: 3

augment:
  cifar10_train:
    random_crop: 32
    padding: 4
    random_horizontal_flip: true

output:
  dir: saved_models/resnet18_cifar10
  csv_log: saved_models/resnet18_cifar10/train_log.csv
