task: vision_classification
dataset: cifar10
model:
  name: resnet18
  num_classes: 10
optimizer:
  name: adam
  lr: 0.001
  weight_decay: 1e-4
training:
  epochs: 2
  batch_size: 128
  num_workers: 2
  val_split: 0.1
  seed: 42
  device: auto
output:
  dir: saved_models/resnet18_cifar10
