task: vision_classification
dataset: mnist
model:
  name: mlp_mnist
  hidden: 256
  num_classes: 10
optimizer:
  name: adam
  lr: 0.001
  weight_decay: 0.0
training:
  epochs: 2
  batch_size: 128
  num_workers: 2
  val_split: 0.1
  seed: 42
  device: auto
output:
  dir: saved_models/mlp_mnist
data:
  root: data/raw
training:
  seed: 42
  pin_memory: true
