task: text_classification
dataset: imdb
model:
  name: tiny_transformer
  vocab_size: 20000
  d_model: 128
  nhead: 4
  num_layers: 2
  num_classes: 2
optimizer:
  name: adam
  lr: 0.0005
training:
  epochs: 2
  batch_size: 32
  num_workers: 2
  seed: 42
  device: auto
output:
  dir: saved_models/transformer_imdb
